version: "3"

services:
  cache:
    image: "redis:alpine"
    container_name: pagoda_cache
    ports:
      - "127.0.0.1:6379:6379"
  db:
    image: postgres:16-alpine
    container_name: pagoda_db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
