// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID                int64          `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	Username          string         `json:"username"`
	HashedPassword    string         `json:"hashed_password"`
	Name              string         `json:"name"`
	Email             string         `json:"email"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	IsActive          bool           `json:"is_active"`
	TenantID          sql.NullString `json:"tenant_id"`
}
